import { h2, hookConfig, p, quote, type Essay } from './types';

export const de: Essay = {
  lang: 'de',
  path: '/de/future-of-ai',
  title: 'Der Loop bewegt sich — maxscopp',
  description:
    'Wie sich KI in der Softwareentwicklung von Human-in-the-Loop zu orchestrierten Agenten bewegt – und was es braucht: richtig konfigurierte Gates, menschliches Urteil, Previews mit einem Klick, geteiltes Memory und Guardrails.',
  eyebrow: 'Essay · Die Zukunft von KI in der Entwicklung',
  heading: 'Der Loop bewegt sich.',
  accent: 'Bewegst du dich mit?',
  intro: [
    'Mensch, ich sag’s dir ganz ehrlich: Die meisten Teams nutzen KI immer noch wie einen schnelleren Praktikanten. Zeile vervollständigen, Funktion hinschmeißen, Frage im Side-Panel beantworten. Klar, das bringt was. Aber der echte Shift? Der ist strukturell.',
    'Menschen steigen aus jedem Tastendruck aus. Rein in Richtung und Urteil. Agenten übernehmen die Ausführung. Automatisierte Gates halten die Qualitätslinie. Und genau diese drei Rollen sauber zu trennen – ohne sie zu vermischen – das ist das ganze Spiel.',
  ],
  blocks: [
    h2('Wo wir stehen: Human-in-the-Loop'),
    p('Heute ist KI Assistent. Du fährst jeden Schritt. Du nickst jede Änderung ab. Der Gewinn ist echt, aber er hat eine harte Deckelung: <strong>Ein Mensch, der in der Mitte jedes Loops liest und entscheidet – in menschlicher Geschwindigkeit.</strong>'),
    p('Das machte Sinn, solange Modelle unzuverlässig waren. Heute, wo sie planen, ausführen und ihre eigene Arbeit prüfen können? Ist genau dieses Modell der Flaschenhals.'),

    h2('Wo’s hingeht: CAO – Continuous Agent Orchestration'),
    p('Beim CAO bewegst du dich <strong>aus dem Loop raus, drüber</strong>. Du definierst Intent, Constraints und was „gut“ aussieht. Agenten zerlegen die Arbeit, laufen parallel, liefern Ergebnisse – keine Vorschläge. Gates entscheiden, ob eine Änderung überhaupt existieren darf. Du entscheidest, ob sie es wert ist, geshippt zu werden.'),
    {
      type: 'table',
      variant: 'shift',
      head: ['', 'Human-in-the-Loop', 'CAO'],
      rows: [
        ['Arbeitseinheit', 'Tastendruck, Funktion, Vorschlag', 'Outcome: Feature, Fix, Migration'],
        ['Mensch', 'Operator – treibt jeden Schritt', 'Director &amp; First User – setzt Intent, prüft Experience'],
        ['KI', 'Assistant – Autocomplete &amp; Chat', 'Agenten, die parallel planen, bauen, fixen'],
        ['Qualität', 'Reviewer-Aufmerksamkeit', 'CI/CD auf jeder Änderung – Pass oder Fail'],
        ['Review', 'Zeile für Zeile, von Hand', 'Gates checken Code; Mensch checkt Produkt'],
        ['Flaschenhals', 'Wie schnell du tippst und liest', 'Wie klar Intent und „Done“ definiert sind'],
      ],
    },

    h2('Drei Rollen, sauber getrennt'),
    p('Der Fehler: „KI“ als einen Brei behandeln, der alles ersetzt. In der Praxis sind es <strong>drei Parteien</strong>, und jede ist gut in etwas, worin die anderen scheitern. Vermischst du sie? Entweder Mensch-Flaschenhals oder unüberwachte Slop-Maschine.'),
    {
      type: 'flow',
      label: 'Der Loop, Schritt für Schritt',
      steps: [
        { who: 'Mensch', step: 'Intent' },
        { who: 'Agenten', step: 'Build' },
        { who: 'Gates', step: 'Pass / Fail', back: 'Fail → zurück an Agenten' },
        { who: 'CI/CD', step: 'Preview ready' },
        { who: 'Mensch', step: 'Nutzen &amp; freigeben' },
        { who: 'Alle', step: 'Shippen &amp; lernen' },
      ],
    },
    {
      type: 'lanes',
      lanes: [
        {
          tag: 'Mensch',
          title: 'Intent',
          lead: 'Rahmt das Problem.',
          items: [
            'Setzt Intent und Acceptance Criteria.',
            'Nutzt das Produkt wie ein echter User.',
            'Jagt Edge Cases, Empty States, Fehler, absurde Inputs.',
            'Urteilt über Interaction, Copy, Accessibility, Feel.',
            'Trifft die Ship-Entscheidung – und trägt die Konsequenzen.',
          ],
        },
        {
          tag: 'Agenten',
          title: 'Build &amp; Iteration',
          lead: 'Wandeln Intent in funktionierende Änderungen. Schnell. Parallel.',
          items: [
            'Planen, implementieren, refactorn.',
            'Schreiben Tests <em>neben</em> dem Code.',
            'Fixen, was Gates ablehnen, und probieren wieder.',
            'Erkunden Varianten, damit du echte Optionen vergleichen kannst.',
            'Dokumentieren Entscheidungen, damit der nächste Agent (oder Mensch) sie lesen kann.',
          ],
        },
        {
          tag: 'Gates',
          title: 'CI/CD, die harte Untergrenze',
          lead: 'Deterministisch. Schwarz-weiß. Jede einzelne Änderung.',
          items: [
            'Linting, Types, Unit/Integration/E2E-Tests.',
            'Static Analysis, CodeQL, Sonar, Dependency-Scans.',
            'Builds, Bundle-Budgets, Perf, a11y.',
            'Immer dieselbe Antwort. Nicht verhandelbar. Nicht überredbar. Nicht müde.',
          ],
        },
      ],
    },

    h2('Gates sind wichtiger denn je'),
    p('Ein Modell findet viele Patterns, die auch CodeQL oder Sonar finden. Heißt nicht, dass die Tools obsolet sind. Heißt: <strong>Sie werden wertvoller.</strong> Sie sind deterministisch. Gleicher Input = gleiches Verdikt. Jedes Mal. In Sekunden. Für fast nichts. Sie werden nicht müde. Man redet sie nicht um. Sie haben keine schlechten Tage.'),
    p('Genau das willst du von einer <em>Minimum Bar</em>. CI/CD wird zum kontinuierlichen, binären Gate auf jeder Änderung: Baut es? Halten Types? Passen Tests? Keine bekannten Vulns? Oder nicht. Merge oder nicht.'),
    p('Agenten sind super darin, diese Bar zu räumen – fütter sie mit Failures, sie fixen sie. Aber sie sind ein <strong>schlechter Ersatz dafür, die Bar <em>zu sein</em></strong>.'),
    p('Und genau dieser garantierte Floor befreit dich. Wenn du vertraust, dass nichts unterhalb der Linie shipped, geht deine Aufmerksamkeit dahin, wo sie hingehört: <strong>Das Produkt.</strong> Du kannst in Details gehen, mehr iterieren, schneller iterieren – ohne jedes Mal die Basics neu zu prüfen.'),

    h2('Wo der Mensch hingehört: Usage Approval'),
    p('Mit Gates, die Code bewachen, und Agenten, die ihn produzieren, wird Zeile-für-Zeile-PR-Review nebensächlich. Spot-Checks okay. Aber jeden Diff lesen? Skaliert nicht. Und dupliziert größtenteils, was Tools schon verifizieren.'),
    p('Deine Approval-Ebene rutscht hoch: Von „ist der Code okay?“ zu <strong>„ist das Produkt richtig?“</strong>'),
    p('Das heißt: <strong>Eigentlich benutzen.</strong> Auf nem echten Device durchklicken. Empty State, Error State, langsames Netz, absurder Input, zweiter User, Tastatur only. Fragen: Wie liest jemand, der das nie sah, das Label? Merken, was sich falsch anfühlt – auch wenn alle Checks grün sind.'),
    p('Automation sagt dir: „Funktioniert wie spezifiziert.“ Nur ein Mensch sagt: „Funktioniert für Menschen.“'),

    h2('Jede abgeschnittene Ecke ist ein Schritt in den Slop'),
    p('Mit Agenten kannst du an <em>jeder</em> Ecke sparen. Und jede sieht einzeln harmlos aus. Geht schneller. Output wirkt plausibel. Heute bricht nix.'),
    {
      type: 'list',
      variant: 'corners',
      items: [
        'Tests „nur diesmal“ skippen, weil der Agent sagte „läuft“',
        'Lint-Regel deaktivieren oder Warning suppressen statt Ursache fixen',
        'Mergen, ohne selbst durchs Feature geklickt zu haben',
        'Generierten Code akzeptieren, den niemand im Team erklären könnte',
        'Architecture Drift zulassen, weil jede Änderung einzeln okay aussah',
        'Happy Path shippen, Edge Cases auf „später“ schieben',
      ],
    },
    quote('<strong>Jede Ecke = ein Schritt in den Slop.</strong> Und Slop compoundiert schneller, als du ihn generieren kannst.'),

    h2('Eine Warnung: Mehr, schneller, chaotischer'),
    p('Zum ersten Mal sind die meisten Teams <strong>nicht mehr durch Output geblockt</strong>. Code, PRs, Features – quasi on demand. Der natürliche Reflex: Reinhauen. Mehr Features. Noch schneller. Noch mehr. Velocity-Charts sehen unglaublich aus.'),
    p('Niemand spürt den Pull stärker als die, deren Job es ist, Dinge voranzutreiben: Dev Leads, PMs, Stakeholders. Meist die motiviertesten im Raum. Jahrelang war ihr Frust: Kapazität. Plötzlich wirkt Kapazität gelöst – die ganze Roadmap erreichbar dieses Quartal. Jedes Gespräch wird zu: „Was können wir noch shippen?“'),
    p('Und dann hört das Produkt auf, Sinn zu ergeben. Features überlappen. Flows widersprechen sich. Niemand erinnert sich, warum was existiert. Jede neue Änderung baut auf einem Layer, den niemand wirklich versteht. Das Team wurde nicht langsamer – es hat nur aufgehört, den Mist zu bemerken, den es shipped.'),
    {
      type: 'note',
      label: 'Ein Hinweis für Leads, PMs und Stakeholders',
      eyebrow: 'Für Leads, PMs, Stakeholders',
      intro: 'Wenn die einzige Richtung „vorwärts“ ist, gehen die Dinge, die Produkte groß machen, als erste – still, weil keine davon im Velocity-Chart auftaucht:',
      items: [
        'Zeit zum Reflektieren: Hat das letzte Feature <em>eigentlich</em> funktioniert?',
        'Es in der echten Welt sehen – echte Daten, echte Devices, echte Workflows, nicht die Demo',
        'Human A/B Judgement: Zwei Versionen nebeneinander, jemand wählt mit Geschmack',
        'Usern und Testern zuhören – das Zögern, der falsche Klick, der Seufzer',
        'Die Iteration <em>nach</em> „es läuft“, wo gut zu großartig wird',
      ],
      close: 'Agenten und Gates machen ein Produkt funktional. <strong>Nur Menschen – reflektierend, beobachtend, zuhörend, vergleichend – machen es großartig.</strong>',
    },
    p('Die Geschwindigkeit ist ein Geschenk, kein Mandat. Nutze sie, um zwei Versionen zu bauen und zu vergleichen. Um etwas <em>heute Nachmittag</em> vor echte User zu stellen statt nächsten Monat. Um am selben Feature dreimal weiterzuiterieren – nicht einfach die nächsten zehn draufzupacken.'),
    p('Die Lektion ist alt und immer noch Gold: <strong>Test. Und bleib dran.</strong> Wissen, was du hast, bevor du mehr draufpackst. Statische Tools helfen hier auch – nicht als Verdikt über einzelne Änderungen, sondern als grober Kompass. Coverage, Complexity, Duplication, Hotspots zeigen dir, wo das Produkt <em>wirklich</em> steht als etwas, das du shippst und maintainable ist: Ein Codebase, den Devs lesen, verstehen und in die Tiefe gehen können, wenn sie müssen. Weil <em>irgendwann immer jemand muss</em>.'),

    h2('Die bessere Geschichte: Richtige Konfiguration, richtig für <em>dich</em>'),
    p('Zwei Teams. Gleiche Agenten. Gleiche Models. Auf Papier gleiche Tools: Formatter, Linter, Type-Checks, Tests, CodeQL, Sonar. Halbjahr später: Eines fliegt, das andere ertrinkt in Noise. Der Unterschied? <strong>Nicht die Tools. Sondern wie sie konfiguriert sind, wo sie laufen, wie sie ins Environment passen.</strong>'),
    p('<strong>Team 1</strong> bolzt Tools drauf. Formatting nur in CI. Jeder Push = Glücksspiel. Agent öffnet PR, wartet 8 Min, scheitert an Trailing Comma, liest Log, fixed, pusht, wartet wieder. Zwei Branches formatieren dieselbe Datei unterschiedlich → Whitespace-Kollision. Import/Key-Order driftet mit dem, wer zuletzt dran war → jeder PR-Update konfliktet. PRs aktuell halten wird stillschweigend zum Job. Review-Threads voll mit Style-Nits. Und wenn ne Regel im Weg ist? Schnellster Fix (Mensch <em>oder</em> Agent): Ausschalten. Sind genau die Gewohnheiten, die wir Devs vor KI hatten – nur schneller und teurer: CI-Minuten, Tokens, Attention für Dinge, die nicht ändern, was das Produkt <em>tut</em>.'),
    p('<strong>Team 2</strong> trifft ein paar Entscheidungen <em>einmal</em>. Schreibt sie als Config nieder. Formatting ist kanonisch und automatisch – zwei Menschen (oder zwei Agenten) schreiben dieselbe Änderung → dieselben Bytes. Imports/Keys sortieren Tools → parallele Branches kämpfen nicht um Order. Whitespace/Line-Endings geklärt durch <code>.editorconfig</code> und <code>.gitattributes</code>. Lint-Regeln, die sich selbst fixen, tun’s; die wenigen übrigen fangen Bugs, nicht Geschmack. Merge-Queue hält PRs aktuell mit Base-Branch und rerunt Gates → niemand babysittet Rebase – und mit kanonischem Formatting konfliktieren Updates fast nie.'),
    {
      type: 'table',
      variant: 'stages',
      head: ['Wo', 'Was läuft', 'Wenn was gefunden wird', 'Cost'],
      rows: [
        ['On Save / Agent Edit', 'Formatter', 'Fixt still', 'Nichts'],
        ['Pre-commit (lefthook)', 'Formatting, Import/Key-Order, Safe Lint Fixes – nur Staged', 'Fixt &amp; re-staged; blockt nie auf Style', 'Millisekunden'],
        ['Pre-push', 'Type-Checks, Affected Tests', 'Stoppt Push, lokal', 'Sekunden'],
        ['CI', 'Alles nochmal + Full/E2E Tests, CodeQL, Sonar, Builds', 'Blockt Merge – die <em>bindende</em> Bar', 'Minuten, Runner'],
        ['Merge Queue', 'Update von Base, Gates rerun', 'Hält PRs aktuell', 'Automatisch'],
      ],
    },
    p('Die billigen, offensichtlichen Fixes passieren <strong>zuerst und lokal</strong>: Alles, was Behavior nicht ändert oder im Worst Case vernachlässigbar. Ein Git-Hook-Manager wie <code>lefthook</code> macht das zur Single File:'),
    { type: 'code', code: hookConfig, lang: 'yaml', title: 'lefthook.yml' },
    p('Biome hier – Prettier, ESLint, Ruff, gofmt funktionieren gleich. Hooks vom Setup-Script des Projekts installieren, damit Agent-Sandboxes sie <em>auch</em> laufen, nicht nur Laptops.'),
    p('Die Kosten folgen derselben Reihenfolge. Pre-commit Fix = Millisekunden, null Tokens. CI-Roundtrip für denselben Trailing Comma = Minuten Runner-Zeit + voller Agent-Turn für Log lesen &amp; Retry – mal jeder PR, jeder Agent, jeder Tag.'),
    p('<strong>Der subtile Part:</strong> CI läuft <em>immer noch</em> jeden Check. Bleibt die bindende, binäre Bar. Wird ein Hook je geskippt, hält die Bar trotzdem. Aber Checks um Form statt Funktion können <strong>nicht mehr scheitern</strong> – bis ein Commit existiert, sind sie schon applied. Die Minimum Bar ist gesichert, <em>bevor</em> sie je getestet wird. Und erzeugt <strong>null Reibung</strong>: Nicht für Menschen. Nicht für Agenten.'),
    quote('Agenten schreiben Code &amp; Features – nicht Formatting. Tools formatieren, sortieren, flaggen. Menschen urteilen über das Produkt.'),
    p('Es gibt kein Universal-Preset zum Kopieren. Die richtige Config ist die, die zu <em>deinem</em> Stack, <em>deinem</em> Repo, <em>deinem</em> CI-Budget, <em>deinem</em> Team passt – einmal entschieden, mit dem Code versioniert, identisch auf jedem Laptop, in jeder Agent-Sandbox, in CI, und schnell genug, dass <strong>niemand je versucht ist, sie zu umgehen</strong>. Hast du das hin, macht jeder das, worin er am besten ist: Tools tun, wofür sie gebaut wurden. Agenten verbraten Iterationen auf Behavior. Menschen verbraten ihre auf das Produkt.'),

    h2('Die Last Mile: Ein Klick von „Done“ zu „Probier’s aus“'),
    p('Zurück zu der Ecke: Mergen, ohne selbst durchs Feature geklickt zu haben. Meist nicht Faulheit. Sondern: <strong>Ausprobieren ist einfach härter, als es sein müsste.</strong> Das ist ein CI/CD-Problem, kein Disziplin-Problem.'),
    p('Agenten schreiben Feature in Minuten. Gut konfigurierte Gates beweisen Minimum Bar Minuten später. Dann erreicht es einen Menschen – und <strong>alles stoppt</strong>. Um’s zu sehen: Branch checkouten, Dependencies installieren, Tokens ausgraben, Migrationen laufen, Seed-Daten, hoffen dass lokales Setup matcht. Lokale KI-Tools und Skills nehmen etwas Grind weg, aber: Context Switch. Minuten bis Stunden. Grund, es zu skippen.'),
    p('<strong>Da sickert die Speed still aus.</strong> Nix gewonnen, wenn Schreiben automatisiert ist, aber Validieren der Flaschenhals bleibt. Gute Gates sagen: „Change ist sound.“ Sie können <em>nicht</em> sagen: „Ist es richtig – für dein Team, für deine User.“ Wenn der Check teuer ist, wird er geskippt. Und die abgeschnittene Ecke wird zum Prozess.'),
    quote('Feature in Minuten schreiben macht dich nicht schnell, wenn Ausprobieren einen Nachmittag frisst.'),
    p('Also: <strong>Ausprobieren zum billigsten Step machen.</strong> Jeder Change bekommt sein eigenes Environment, gebaut von der Pipeline:'),
    {
      type: 'list',
      variant: 'ready',
      items: [
        'Ein Link für jeden Change – oder installierbarer Build für Apps, Desktop, CLIs',
        'Eigene Daten: Migrationen applied, realistischer Seed, Test-Accounts ready',
        'Secrets &amp; Integrationen schon verdrahtet, niemand reicht Tokens rum',
        'Dieselben Gates &amp; Config wie Prod – nur disposable',
        'Auto Teardown bei Merge oder Close',
        'Notification, wenn ready – kein Dashboard, das du beobachten musst',
      ],
    },
    {
      type: 'toast',
      title: 'Hey, ich bin fertig — dein Preview ist ready',
      meta: 'checkout-redesign · gates passed · migrations applied',
      primary: 'Open Preview',
      secondary: 'Download Build',
      time: 'now',
      caption: 'So muss „Done“ aussehen: Ein Ping. Ein Link. Eine Entscheidung.',
    },
    p('Dann schließt sich der Loop, wie er soll. Agent fertig, Gates grün, du kriegst Ping. Klickst Link oder lädst Build runter. Nutzt es wie ein User. Stupst Edge Cases an. Entscheidest – Ship it, oder nächste Schritte &amp; Fokus an Agenten zurück. <strong>Minuten. Nicht Nachmittag.</strong> Das ist „schnell mit Confidence“: Nicht nur schneller Output. Sondern schnelles, billiges, ehrliches Validieren.'),

    h2('Warum KI in Enterprise-Workflows klobig wird'),
    p('Die meisten großen Orgas adoptieren KI gleich: Bestehenden Prozess nehmen – Tickets, Handoffs, Approvals, Sprint-Ceremonies – und jedem Step einen Assistant spendieren. Fühlt sich safe an. Demot gut. Aber: <strong>Der Prozess wurde um menschliche Flaschenhälse designed.</strong> Ein System bewegt sich nur so schnell wie sein langsamstes Gate.'),
    {
      type: 'frictions',
      items: [
        { title: 'Mensch-Gates, dimensioniert für Mensch-Output', text: 'Agent liefert working Change in Minuten. Automated Checks verifizieren in Minuten mehr. Dann wartet es Tage auf Ticket-Refinement, Review-Slot, Change-Advisory-Board, Release-Train – alles designed um Menschen-Pace. Der Speedup verdunstet in der Queue.' },
        { title: 'Context in Köpfen &amp; Meetings gefangen', text: 'Agenten sind nur so gut wie ihr Context. Wenn Requirements in Flurgesprächen, Tribal Knowledge und Slide Decks leben, ratet die KI – und Menschen verbringen die gesparte Zeit damit, sie zu korrigieren.' },
        { title: 'Tools &amp; Permissions für Menschen gebaut', text: 'Access pro Mensch. Environments hand-provisioned. Nix safe für unattended Run. Agenten landen in Sandboxes so eng, dass sie keine echte Arbeit können. Oder gar nicht erst.' },
        { title: 'Metriken, die den alten Prozess messen', text: 'Story Points, Closed Tickets, Lines of Code = Proxies für menschlichen Effort. Mit alten Yardsticks gemessen wirkt KI entweder wundersam oder nutzlos – selten das, was sich für User <em>wirklich</em> geändert hat.' },
        { title: 'KI als Feature, nicht als Rethink', text: 'Chat-Assistant an jedes Team ausrollen = einfach anzukündigen, einfach in Lizenzen zu messen. Verbessert einzelne Tasks um paar Prozent. Während das System drumherum <em>genau so langsam bleibt</em>.' },
      ],
    },
    quote('Einzelne Steps in einem für Menschen gebauten Prozess zu beschleunigen, macht meist <strong>die Queues länger</strong>. Arbeit wird schneller. Outcome nicht.'),
    p('Meine Erwartung: Die meisten Firmen, die so rangehen, werden kämpfen, meaningful Improvement zu zeigen. Sie sehen Produktivitäts-Inseln, viele Lizenzen, und eine Delivery-Speed, die verdächtig nach letztem Jahr aussieht. Nicht weil Models nicht gut genug sind – sondern weil die Orga nie redesigned wurde, sie zu nutzen.'),

    h2('Geteiltes Memory, unterschiedliche Perspektiven'),
    p('Zwei dieser Reibungen – Context in Köpfen, Tools für Menschen – sind keine Prozess-Probleme. <strong>Infrastruktur-Probleme.</strong> Mit Infrastruktur-Antworten. Das erste: Memory.'),
    p('Persönliches Projekt? Memory ist simpel: Claude Code starten, Memory an, es lernt nach und nach Codebase, Conventions, Preferences. Ein Mensch, ein Repo – reicht.'),
    p('In der Orga bricht das Modell. Jeder Agent startet bei Null. Eigenes Repo. Eigene Sandbox. Eigene Session. Agent im Payments-Service weiß nicht, was Checkout-Team letzte Woche entschied. Agent in Mobile App weiß nicht, dass die API, die er ruft, retired wird. Niemand erinnert sich, warum zwei Produkte einen Login teilen. Jeder Agent: <strong>lokal korrekt, global lost.</strong>'),
    p('Also muss Memory <strong>Shared Infrastructure</strong> werden: Verfügbar für jeden Agent, an jedem Step, across Products &amp; Microservices. Product Principles. Architecture. Contracts zwischen Services. Entscheidungen <em>und ihr Why</em>. Vocabulary. Known Pitfalls. Damit selbst ein Agent in isoliertem Repo/Environment weiß: Andere Produkte existieren. Was sie erwarten. Wie alles zusammenhält. Das fehlende Piece, das die meisten Multi-Repo-Orgas nie hatten – <strong>nicht mal für ihre Menschen.</strong>'),
    p('Und es muss <strong>von Menschen orchestrierbar</strong> sein. Memory ist, wo Menschen at Scale steuern: Falsche Annahme einmal korrigieren → jeder Agent hört auf, sie zu machen. Priority shiften → jeder Agent sieht es. Heißt: Owned, Reviewable, Versioned. Kein Haufen Chat-Transkripte, den niemand editieren kann.'),
    {
      type: 'memory',
      label: 'Agenten, die dasselbe Memory lesen, jeder mit eigener Perspektive',
      tag: 'Shared Memory',
      items: 'Principles · Architecture · Contracts · Decisions &amp; Why · Vocabulary · Known Pitfalls',
      owner: 'curated by people',
      perspectives: [
        { lens: 'Goalpost', title: 'Refined das Goal', text: 'Was lösen wir, für wen, was ist Success? Bewegt das Target mit jedem Learning.' },
        { lens: 'Acceptance', title: 'Definiert „Done“', text: 'Intent → Criteria, Edge Cases, Tests, gegen die alle bauen &amp; checken.' },
        { lens: 'Usability', title: 'Urteilt über die Experience', text: 'Läuft Flows wie ein User – Clarity, a11y, Empty/Error States, Feel.' },
        { lens: 'Architecture', title: 'Guarded die Seams', text: 'Prüft jeden Change gegen die Contracts zwischen Produkten/Services.' },
      ],
    },
    p('Der Key: <strong>Agenten mit Perspektiven.</strong> Alle lesen dasselbe Memory. Aber jeder fokussiert einen anderen Aspekt. Einer refined den Goalpost. Einer owned Acceptance. Einer judged Usability. Einer guarded die Seams. Selbe Facts, verschiedene Linsen. Wenn sie disagreen → surfaced es früh, offen, wo ein Mensch es settlen kann – statt spät, in Prod.'),

    h2('Guardrails: Dein Geschmack, aufgeschrieben'),
    p('Agenten können viel – <strong>genau deshalb müssen sie wissen, was sie NICHT tun sollen.</strong> Jedes Product hat seinen eigenen Geschmack an Do’s und Don’ts: Patterns, die du nutzt, die du gebannt hast. Libraries, denen du vertraust. Wie Errors gehandhabt werden. Was nie in Logs geht. Welche Daten nie die Region verlassen. Wie das Interface mit Menschen redet. Wann fragen statt raten.'),
    p('Diese Regeln verdienen dieselbe Behandlung wie CI/CD-Tooling: <strong>Aufgeschrieben. Versioned. Reviewed. Überall automatisch angewendet.</strong> Aber ein großer Unterschied: Lint-Config = einmal gesetzt, selten angefasst. Guardrails <strong>leben mit dem Product</strong> – sie ändern sich, während es reift, das Team lernt, Markt &amp; Regulation sich bewegen. Sie brauchen Owner, History, Platz im regulären Gespräch.'),
    {
      type: 'table',
      variant: 'compare',
      head: ['', 'Lint &amp; CI Config', 'Guardrails'],
      rows: [
        ['Encodiert', 'Form &amp; bekannte Bug-Patterns', 'Geschmack, Boundaries, Judgement'],
        ['Ändert sich', 'Selten, wenn überhaupt', 'Kontinuierlich, mit dem Product'],
        ['Gecheckt von', 'Deterministische Tools', 'Agenten, Reviewer, Menschen'],
        ['Geschrieben für', 'Maschinen', 'Agenten <strong>und</strong> Developer gleichermaßen'],
      ],
    },
    p('Die letzte Row ist wichtiger, als sie aussieht. Guardrails sollen <strong>nicht exklusiv für Agenten</strong> sein. Gut geschrieben sind sie das klarste Statement darüber, wie <em>dein Team baut</em> – und halten genauso im Kopf eines Developers. Dieselbe Page, die den Agent stoppt, noch ne State-Lib hinzuzufügen, erinnert den New Hire, <em>warum</em> ihr das nicht tut – und gibt dem Reviewer was Besseres als „Gefällt mir nicht.“'),
    quote('Wenn ne Regel nur im Prompt lebt, ist sie kein Guardrail – sie ist ein Secret.'),
    p('Was uns zum Step bringt, den die meisten Orgas verpassen: <strong>Die richtige Infrastructure für die Architecture.</strong> Wenn jedes Team seine eigenen Agenten verdrahtet, endet jedes Repo mit eigener Guardrails-Kopie, eigenen MCP-Servern, eigenen Keys, eigener Idee von „erlaubt“ – ab Tag 1 auseinanderdriftend. <strong>Shared Pieces an einen Ort packen:</strong> Ein Gateway vor Inference (oder Proxy davor), durch das <strong>jeder</strong> Agent und <strong>jedes</strong> Developer-Tool geht.'),
    {
      type: 'gateway',
      clients: [
        { who: 'Agent', where: 'checkout repo' },
        { who: 'Agent', where: 'payments service' },
        { who: 'Agent', where: 'CI pipeline' },
        { who: 'Developer', where: 'IDE' },
      ],
      title: 'One Gateway to Inference',
      sub: 'oder Proxy davor — jeder Agent &amp; jedes Dev-Tool geht hier durch',
      chips: ['Guardrails', 'Shared Memory', 'Shared MCP Servers', 'Access &amp; Audit', 'Cost &amp; Model Routing'],
      models: 'Models',
      caption: 'Isoliert, wo es zählt. Geteilt, wo es sein sollte.',
    },
    p('Da werden Guardrails angewendet. Da wird Memory geservt. Da werden MCP-Server geteilt statt in jedem Repo re-implementiert. Da werden Access, Audit, Cost, Model Choice <strong>einmal</strong> gemanagt. Guardrail einmal ändern → jeder Agent kriegt’s beim nächsten Request mit. Das ist kein Overhead. Das ist, was <strong>100 Agenten wie ein Team verhalten lässt.</strong>'),

    h2('Was stattdessen funktioniert'),
    p('Teams, die Step-Changes hinbekommen, <strong>fügen KI nicht ihrem Workflow hinzu – sie bauen den Workflow neu</strong>, sodass Menschen, Agenten, Gates jeweils das tun, worin sie am besten sind.'),
    {
      type: 'list',
      variant: 'checklist',
      items: [
        '<strong>Intent &amp; Acceptance Criteria upfront definieren</strong> – klar genug, dass der Agent weiß, wann er done ist.',
        '<strong>In Gates investieren, bevor Agenten kommen:</strong> Strenges Linting, Types, Tests, CodeQL/Sonar, Preview Builds auf <em>jeder</em> Änderung.',
        '<strong>Tools fixen lassen, was sie können, <em>bevor</em> committed wird</strong> – Formatting, Whitespace, Import/Key-Order – damit CI nie auf Style scheitert und niemand es reviewed.',
        '<strong>Memory zur Shared Infrastructure machen:</strong> Principles, Architecture, Contracts, Decisions für jeden Agent an jedem Step verfügbar – curated &amp; korrigierbar von Menschen.',
        '<strong>Guardrails wie Config aufschreiben, aber lebendig halten</strong> – Owned, Versioned, mit Developern geteilt, aus einem Gateway serviert zusammen mit Memory &amp; MCP-Servern.',
        '<strong>Agenten echte, scoped Environments geben</strong> – Safe für Unattended, easy zum Wegwerfen.',
        '<strong>Jedem Change ein Preview geben</strong> – Link oder installierbarer Build, mit Daten &amp; Secrets verdrahtet – und Ping, wenn ready, damit Human Review vom Diff zum Produkt rutscht.',
        '<strong>Teams klein &amp; Ownership End-to-End</strong> – damit der Loop von Idee zu Shipped nicht über Handoffs zersplittert.',
        '<strong>Outcomes messen, nicht Output:</strong> Zeit schützen für Reflektion, echte User beobachten, Optionen Side-by-Side vergleichen – <strong>da wird gut zu großartig.</strong>',
        '<strong>Klein anfangen, End-to-End:</strong> Ein Product, ein Team, ein Value Stream <em>richtig</em> redesigned schlägt KI über 100 unveränderte Prozesse gestreut.',
      ],
    },
    p('Je mehr Arbeit Agenten übernehmen, desto mehr wird der menschliche Part – <strong>Geschmack, Urteil, Empathie für die Leute, die das Ding nutzen, und Accountability, wenn es shipped</strong> – zum eigentlichen Job.'),
    h2('Aus der Praxis: Der Staff Engineer'),
    p('Mensch, ich sitz hier und schau mir an, was gerade in den Teams um mich herum passiert. Und ehrlich? Die Hälfte hätte ich vor einem Jahr noch für Science-Fiction gehalten.'),
    p('Da ist dieser Senior-Entwickler bei einem Mittelständler in der Nähe von Frankfurt. Letztes Jahr noch Lead Developer. Heute? Er hat sich „degradiert“ – offiziell nur noch „Staff Engineer“. Kein Team mehr, keine Personalverantwortung, keine Sprint-Plannings mehr moderieren. <strong>Und verdient trotzdem deutlich mehr als vorher.</strong> Weil er endlich das tut, wofür er eigentlich bezahlt wird: Architekturentscheidungen treffen. Produktvision in technische Realität übersetzen. Erfahren genug sein, um zu sagen: „Das wird in sechs Monaten scheitern, weil …“ – und die Agenten dann die Details ausarbeiten lassen, während er schon beim nächsten Hebel ansetzt.'),
    p('Der Typ tippt kaum noch Code. Er <em>denkt</em> Code. Und die Agenten? Die tippen. Parallel. Zehn Dateien gleichzeitig. Tests dazu. Dokumentation gleich mit. Er reviewt nur noch die Stellen, wo Erfahrung den Unterschied macht: Schnittstellen zwischen Services. Datenmodelle, die überleben müssen. Die eine Abstraktion, die entweder alles trägt oder alles bricht.'),
    p('Die drei Rollen haben sich nicht in einem Meeting entschieden. Die sind einfach passiert.'),
    p('<strong>Mensch – Intent.</strong> Nicht „User Stories schreiben“. Sondern: Mit dem Product Owner am Whiteboard stehen und streiten: „Bauen wir das <em>jetzt</em> oder ziehen wir erst das Technical Debt aus dem Zahlungsmodul? Weil wenn wir das nicht tun, blockiert uns der nächste Feature-Request drei Monate lang.“ Der Stakeholder will alles gestern. Der Mensch übersetzt: „Okay, wir liefern Feature X in zwei Wochen – aber nur, wenn wir <em>gleichzeitig</em> den Refactor im Auth-Service machen. Agent, plan das mal durch.“'),
    p('<strong>Agent – Build.</strong> Der kriegt den Auftrag: „Refactor Auth-Service <em>und</em> Feature X parallel. Hier sind die Constraints: Keine Breaking Changes an der API. Tests müssen grün bleiben. Migration muss rollback-fähig sein.“ Und der Agent? Der fängt <em>sofort</em> an. Nicht nach Sprint-Start. Nicht nach Ticket-Refinement. Sofort. Er schreibt den Migrationsplan. Er schreibt die Tests <em>für den neuen Code</em>, bevor der neue Code existiert. Er probiert drei Varianten durch – eine mit Event-Sourcing, eine klassisch, eine hybrid – und legt dem Menschen morgens um 8:30 drei PRs vor: „Option A: sicherer, zwei Wochen. Option B: schneller, technisches Risiko hier. Option C: sauberste Architektur, aber drei Tage mehr Arbeit.“'),
    p('<strong>Gates – Pass/Fail.</strong> Die Gates? Die schlafen nicht. Die prüfen <em>jede</em> Variante. Types, Lint, Unit, Integration, E2E, CodeQL, Sonar, Bundle-Size, a11y. Variante B fällt raus – der Security-Scan findet was. Variante A und C laufen durch. Der Mensch klickt sich durch die Previews (die <em>automatisch</em> gebaut wurden, mit echten Daten, echten Secrets, echtem Everything), probiert die Edge Cases aus, nickt bei Option C: „Nimm die. Merge. Ship.“'),
    p('Während er das entscheidet, haben die Agenten längst angefangen, das nächste Ding vorzubereiten. Weil sie den Kontext haben. Weil sie das Memory teilen. Weil sie wissen: „Ah, der Auth-Refactor ist durch – dann kann ich jetzt das Feature-Flag für die neue Payment-Methode schon mal sauber einbauen.“'),

    h2('Was das mit Rollen macht'),
    quote('Das Crazy: <strong>Das passiert schon. Heute. In echten Firmen.</strong>'),
    p('Nicht in Demos. Nicht in Side-Projects. In Produktionssystemen, die Geld verdienen.'),
    p('Die normalen Devs? Viele gehen. Nicht, weil sie schlecht sind – sondern weil sie <em>nur</em> coden können. Und Coden ist jetzt die billigste Aktivität im ganzen Stack. Wer „nur“ Tickets abarbeitet, wird ersetzt. Nicht von KI – von <strong>einem Senior + Agenten</strong>, der das Zehnfache durchzieht.'),
    p('Die, die bleiben? Die werden <em>wertvoller</em>. Viel wertvoller. Weil ihre Kompetenz plötzlich <strong>skaliert</strong>. Ein Architect, der früher drei Teams betreuen konnte, betreut jetzt fünfzehn – weil die Agenten die Fleißarbeit machen, die früher Junior-Entwickler gemacht haben. Und die Juniors? Die gibt’s kaum noch. Zumindest nicht im klassischen Sinn. Die Junior-Rolle verschiebt sich: Wer neu anfängt, lernt nicht „Wie schreibe ich eine Funktion?“ – sondern „Wie formuliere ich Intent so präzise, dass der Agent das Richtige baut?“ und „Wie erkenne ich, ob das Ergebnis <em>wirklich</em> gut ist?“'),

    h2('Menschen arbeiten immer noch mit Menschen'),
    p('Aber – und das ist der Teil, den die ganzen „KI ersetzt Programmierer“-Artikel nie verstehen – <strong>Menschen arbeiten immer noch primär mit Menschen.</strong>'),
    p('Feature-Priorisierung? Ein Agent kann dir eine Liste von 200 Tasks generieren, sauber geschätzt, mit Dependencies, Risiken, Impact-Scores. Beeindruckend. Aber <em>welche</em> davon wir <em>jetzt</em> bauen? Das verhandelt ein Mensch mit Stakeholdern. Das ist Politik. Das ist Vertrauen. Das ist: „Kunde X droht abzuhauen, wenn wir Feature Y nicht nächsten Monat liefern – aber wenn wir Y bauen, brechen wir Z für Kunde A, unseren größten Umsatzbringer. Was tun wir?“'),
    quote('Kein Agent entscheidet das. Kein Agent <em>soll</em> das entscheiden.'),
    p('Was der Agent <em>kann</em>: Er sagt dir: „Wenn wir Y bauen, brechen wir Z <em>hier</em> und <em>hier</em> – hier sind die betroffenen Tests, hier der Migrationsaufwand, hier drei Optionen, wie wir Z retten können. Option 1 kostet zwei Wochen. Option 2 kostet drei Tage, aber wir brauchen ein Feature-Flag. Option 3: Wir sagen Kunde A, dass er migrieren muss – hier ist der Migrationsleitfaden, den ich schon mal vorbereitet habe.“'),
    p('Der Mensch entscheidet. In Minuten. Nicht in zwei Wochen Architecture-Review-Meetings.'),

    h2('Refactor zuerst – mit Zahlen statt Bauchgefühl'),
    p('Refactoring vor neuem Feature? Früher: „Machen wir später. Jira-Ticket erstellen. Vergessen.“ Heute: Der Agent analysiert die Codebase, findet die Hotspots, simuliert den Impact: „Wenn wir Feature X <em>ohne</em> Refactor bauen, steigt die Change-Failure-Rate im Payment-Modul um 34 %. Der Refactor kostet 4 Agenten-Tage. Feature X allein 6 Tage. Feature X <em>mit</em> Refactor 8 Tage – aber danach ist das nächste Feature 40 % schneller.“ Der Mensch sieht die Zahlen. Nickt. „Mach den Refactor zuerst. Ich sag dem PO, dass Feature X zwei Tage später kommt, aber die nächsten drei Features schneller gehen.“'),
    p('Und während der Mensch das dem PO erklärt, hat der Agent den Refactor <em>schon gestartet</em>. Nicht „geplant“. Gestartet. Branches erstellt. Tests geschrieben. Erste Commits gepusht. CI läuft. Previews stehen bereit.'),

    h2('Keine Zukunftsmusik: letzten Dienstag'),
    p('Das ist keine Zukunftsmusik. Das ist <strong>letzten Dienstag</strong> passiert. In einem Team, das ich kenne. Fünf Leute. Zwei Senior, ein Mid, zwei „Agenten-Orchestratoren“ – eine neue Rolle mit eigenem Gehaltsband. Sie haben in einer Woche geshippt, wofür sie früher sechs gebraucht hätten. Mit <em>besserer</em> Code-Quality. Weil die Gates nicht müde werden. Weil die Agenten nicht „schnell, schnell“ machen, sondern „richtig, richtig“ – weil der Mensch ihnen gesagt hat, wie „richtig“ aussieht.'),
    p('Und das Beste? <strong>Die Senior-Entwickler gehen wieder mit Freude nach Hause.</strong> Nicht, weil sie weniger arbeiten – sondern weil sie <em>das Richtige</em> arbeiten. Architektur. Produkt. Mentoring. Die Entscheidungen, die Erfahrung brauchen. Das Tippen? Erledigen die Agenten. Während der Mensch Kaffee trinkt und mit dem Product Owner streitet.'),
    p('Die Firmen, die das kapiert haben? Die stellen gerade ein. Nicht „Entwickler“. <strong>Architekten mit Agenten-Flotten.</strong> Und bezahlen sie entsprechend.'),
    p('Die Firmen, die noch „KI-Assistenten in Jira integrieren“? Die werden nächstes Jahr fragen, warum ihre Velocity nicht gestiegen ist – während ihre besten Leute kündigen, weil sie woanders für genau die Arbeit, die sie <em>eigentlich</em> gelernt haben, deutlich besser bezahlt werden.'),

    h2('Die neue Seniorität'),
    p('Oben ging’s um YAML-Configs. Lefthook-Setups. Gateway-Architekturen für Shared Memory. Guardrails als Code. Preview-Pipelines, die dir für jeden PR einen klickbaren Link in Slack posten.'),
    p('Aber ehrlich? Das sind nur Werkzeuge. Das eigentliche Spiel findet <strong>zwischen den Ohren</strong> statt. Und in den Gesprächen am Whiteboard. Und in der Frage, die du dir jeden Morgen stellst:'),
    quote('Was ist heute der Hebel, den nur ich bewegen kann – und wie bringe ich die Agenten dazu, den Rest zu bauen?'),
    p('Das ist die neue Seniorität. Nicht „Ich codiere am schnellsten“. Sondern: „Ich weiß, was gebaut werden muss – und ich habe die Armee, die es baut, während ich schon den nächsten Hebel suche.“'),
    p('Genau deshalb designe und baue ich so.'),
    {
      type: 'cta',
      text: 'Überlegst du, wie das in <em>deinem</em> Setup aussieht? Was dein erster Hebel wäre?',
      sub: 'Lass uns drüber reden. Kein Pitch. Kein Bullshit. Nur zwei Leute, die das gleiche Problem aus unterschiedlichen Winkeln sehen.',
      button: 'Lass uns reden',
    },
  ],
};
