import { h2, hookConfig, p, quote, type Essay } from './types';

export const en: Essay = {
  lang: 'en',
  path: '/future-of-ai',
  title: 'The loop is moving — maxscopp',
  description:
    'How AI in software development is moving from human-in-the-loop to orchestrated agents — and what it takes: quality gates set up right, human judgement, one-click previews, shared memory and guardrails.',
  eyebrow: 'Essay · Future of AI in development',
  heading: 'The loop is moving.',
  accent: 'Are you moving with it?',
  intro: [
    'Look, I’ll be honest with you: most teams still use AI like a faster intern. Finish the line, knock out a function, answer a question in the side panel. Sure, that helps. But the real shift? It’s structural.',
    'People step out of every keystroke. Into direction and judgement. Agents take over execution. Automated gates hold the quality line. And keeping those three roles cleanly apart – without mixing them up – that’s the whole game.',
  ],
  blocks: [
    h2('Where we are: human-in-the-loop'),
    p('Today, AI is an assistant. You drive every step. You sign off every change. The gain is real, but it has a hard ceiling: <strong>one person reading and deciding in the middle of every loop – at human speed.</strong>'),
    p('That made sense while models were unreliable. Today, when they can plan, execute and check their own work? That exact model is the bottleneck.'),

    h2('Where it’s going: CAO – Continuous Agent Orchestration'),
    p('With CAO, you move <strong>out of the loop and above it</strong>. You define intent, constraints and what “good” looks like. Agents break the work down, run in parallel and deliver results – not suggestions. Gates decide whether a change is even allowed to exist. You decide whether it’s worth shipping.'),
    {
      type: 'table',
      variant: 'shift',
      head: ['', 'Human-in-the-loop', 'CAO'],
      rows: [
        ['Unit of work', 'Keystroke, function, suggestion', 'Outcome: feature, fix, migration'],
        ['Human', 'Operator – drives every step', 'Director &amp; first user – sets intent, checks the experience'],
        ['AI', 'Assistant – autocomplete &amp; chat', 'Agents that plan, build and fix in parallel'],
        ['Quality', 'Reviewer attention', 'CI/CD on every change – pass or fail'],
        ['Review', 'Line by line, by hand', 'Gates check the code; people check the product'],
        ['Bottleneck', 'How fast you type and read', 'How clearly intent and “done” are defined'],
      ],
    },

    h2('Three roles, cleanly separated'),
    p('The mistake: treating “AI” as one mush that replaces everything. In practice there are <strong>three parties</strong>, and each is good at something the others fail at. Mix them up? You get either a human bottleneck or an unsupervised slop machine.'),
    {
      type: 'flow',
      label: 'The loop, step by step',
      steps: [
        { who: 'Human', step: 'Intent' },
        { who: 'Agents', step: 'Build' },
        { who: 'Gates', step: 'Pass / fail', back: 'fail → back to agents' },
        { who: 'CI/CD', step: 'Preview ready' },
        { who: 'Human', step: 'Use &amp; approve' },
        { who: 'All', step: 'Ship &amp; learn' },
      ],
    },
    {
      type: 'lanes',
      lanes: [
        {
          tag: 'Human',
          title: 'Intent',
          lead: 'Frames the problem.',
          items: [
            'Sets intent and acceptance criteria.',
            'Uses the product like a real user.',
            'Hunts edge cases, empty states, errors, absurd inputs.',
            'Judges interaction, copy, accessibility, feel.',
            'Makes the ship call – and owns the consequences.',
          ],
        },
        {
          tag: 'Agents',
          title: 'Build &amp; iteration',
          lead: 'Turn intent into working changes. Fast. In parallel.',
          items: [
            'Plan, implement, refactor.',
            'Write tests <em>alongside</em> the code.',
            'Fix what the gates reject, and try again.',
            'Explore variants so you can compare real options.',
            'Document decisions so the next agent (or person) can read them.',
          ],
        },
        {
          tag: 'Gates',
          title: 'CI/CD, the hard floor',
          lead: 'Deterministic. Black and white. Every single change.',
          items: [
            'Linting, types, unit/integration/E2E tests.',
            'Static analysis, CodeQL, Sonar, dependency scans.',
            'Builds, bundle budgets, perf, a11y.',
            'Always the same answer. Not negotiable. Not persuadable. Never tired.',
          ],
        },
      ],
    },

    h2('Gates matter more than ever'),
    p('A model finds many of the patterns CodeQL or Sonar find too. Doesn’t mean the tools are obsolete. It means: <strong>they become more valuable.</strong> They’re deterministic. Same input = same verdict. Every time. In seconds. For almost nothing. They don’t get tired. You can’t talk them round. They don’t have bad days.'),
    p('That’s exactly what you want from a <em>minimum bar</em>. CI/CD becomes a continuous, binary gate on every change: Does it build? Do the types hold? Do the tests pass? No known vulns? Or not. Merge or no merge.'),
    p('Agents are great at clearing that bar – feed them the failures and they fix them. But they’re a <strong>poor substitute for <em>being</em> the bar</strong>.'),
    p('And that guaranteed floor is what frees you. When you trust that nothing below the line ships, your attention goes where it belongs: <strong>the product.</strong> You can go into the details, iterate more, iterate faster – without re-checking the basics every time.'),

    h2('Where the human belongs: usage approval'),
    p('With gates guarding the code and agents producing it, line-by-line PR review becomes a side issue. Spot checks, fine. But reading every diff? Doesn’t scale. And mostly duplicates what the tools already verify.'),
    p('Your approval moves up a level: from “is the code okay?” to <strong>“is the product right?”</strong>'),
    p('That means: <strong>actually using it.</strong> Click through on a real device. Empty state, error state, slow network, absurd input, second user, keyboard only. Ask: how does someone who’s never seen it read that label? Notice what feels off – even when every check is green.'),
    p('Automation tells you: “works as specified.” Only a person tells you: “works for people.”'),

    h2('Every corner cut is a step into slop'),
    p('With agents, you can cut <em>every</em> corner. And each one looks harmless on its own. It’s faster. The output looks plausible. Nothing breaks today.'),
    {
      type: 'list',
      variant: 'corners',
      items: [
        'Skipping tests “just this once” because the agent said “it works”',
        'Disabling a lint rule or suppressing a warning instead of fixing the cause',
        'Merging without clicking through the feature yourself',
        'Accepting generated code nobody on the team could explain',
        'Letting architecture drift because every change looked fine on its own',
        'Shipping the happy path and pushing edge cases to “later”',
      ],
    },
    quote('<strong>Every corner = a step into slop.</strong> And slop compounds faster than you can generate it.'),

    h2('A warning: more, faster, messier'),
    p('For the first time, most teams are <strong>no longer blocked by output</strong>. Code, PRs, features – practically on demand. The natural reflex: go all in. More features. Even faster. Even more. Velocity charts look incredible.'),
    p('Nobody feels that pull harder than the people whose job is to push things forward: dev leads, PMs, stakeholders. Usually the most motivated people in the room. For years, their frustration was capacity. Suddenly capacity seems solved – the whole roadmap reachable this quarter. Every conversation turns into: “What else can we ship?”'),
    p('And then the product stops making sense. Features overlap. Flows contradict each other. Nobody remembers why anything exists. Every new change builds on a layer nobody really understands. The team didn’t get slower – it just stopped noticing the mess it ships.'),
    {
      type: 'note',
      label: 'A note for leads, project managers and stakeholders',
      eyebrow: 'For leads, PMs, stakeholders',
      intro: 'When the only direction is “forward”, the things that make products great are the first to go – quietly, because none of them show up on a velocity chart:',
      items: [
        'Time to reflect: did the last feature <em>actually</em> work?',
        'Seeing it in the real world – real data, real devices, real workflows, not the demo',
        'Human A/B judgement: two versions side by side, and someone choosing with taste',
        'Listening to users and testers – the hesitation, the wrong click, the sigh',
        'The iteration <em>after</em> “it works”, where good becomes great',
      ],
      close: 'Agents and gates make a product work. <strong>Only people – reflecting, watching, listening, comparing – make it magnificent.</strong>',
    },
    p('The speed is a gift, not a mandate. Use it to build two versions and compare them. To put something in front of real users <em>this afternoon</em> instead of next month. To iterate on the same feature three more times – not just pile the next ten on top.'),
    p('The lesson is old and still gold: <strong>Test. And keep up.</strong> Know what you have before you pile on more. Static tools help here too – not as a verdict on individual changes, but as a rough compass. Coverage, complexity, duplication, hotspots show you where the product <em>really</em> stands as something you’d ship, and whether it’s still maintainable: a codebase devs can read, understand and dig into when they have to. Because <em>eventually, someone always has to</em>.'),

    h2('The better story: the right configuration, right for <em>you</em>'),
    p('Two teams. Same agents. Same models. On paper, the same tools: formatter, linter, type checks, tests, CodeQL, Sonar. Six months later: one is flying, the other is drowning in noise. The difference? <strong>Not the tools. How they’re configured, where they run, and how they fit into the environment.</strong>'),
    p('<strong>Team 1</strong> bolts the tools on. Formatting only in CI. Every push = a gamble. An agent opens a PR, waits 8 minutes, fails on a trailing comma, reads the log, fixes it, pushes, waits again. Two branches format the same file differently → whitespace collision. Import and key order drift with whoever touched the file last → every PR update conflicts. Keeping PRs current quietly becomes a job. Review threads fill up with style nits. And when a rule gets in the way? Fastest fix (human <em>or</em> agent): switch it off. These are exactly the habits we devs had before AI – just faster and more expensive: CI minutes, tokens and attention spent on things that don’t change what the product <em>does</em>.'),
    p('<strong>Team 2</strong> makes a few decisions <em>once</em>. Writes them down as config. Formatting is canonical and automatic – two people (or two agents) writing the same change → the same bytes. Tools sort imports and keys → parallel branches don’t fight over order. Whitespace and line endings are settled by <code>.editorconfig</code> and <code>.gitattributes</code>. Lint rules that can fix themselves do; the few that remain catch bugs, not taste. A merge queue keeps PRs current with the base branch and reruns the gates → nobody babysits a rebase – and with canonical formatting, updates almost never conflict.'),
    {
      type: 'table',
      variant: 'stages',
      head: ['Where', 'What runs', 'When it finds something', 'Cost'],
      rows: [
        ['On save / agent edit', 'Formatter', 'Fixes it silently', 'Nothing'],
        ['Pre-commit (lefthook)', 'Formatting, import/key order, safe lint fixes – staged files only', 'Fixes &amp; re-stages; never blocks on style', 'Milliseconds'],
        ['Pre-push', 'Type checks, affected tests', 'Stops the push, locally', 'Seconds'],
        ['CI', 'Everything again + full/E2E tests, CodeQL, Sonar, builds', 'Blocks the merge – the <em>binding</em> bar', 'Minutes, runners'],
        ['Merge queue', 'Update from base, rerun the gates', 'Keeps PRs current', 'Automatic'],
      ],
    },
    p('The cheap, obvious fixes happen <strong>first, and locally</strong>: anything that doesn’t change behaviour, or changes it negligibly at worst. A git hook manager like <code>lefthook</code> turns that into a single file:'),
    { type: 'code', code: hookConfig, lang: 'yaml', title: 'lefthook.yml' },
    p('Biome here – Prettier, ESLint, Ruff and gofmt work the same way. Install the hooks from the project’s setup script, so agent sandboxes run them <em>too</em>, not just laptops.'),
    p('The costs follow the same order. Pre-commit fix = milliseconds, zero tokens. A CI round trip for the same trailing comma = minutes of runner time + a full agent turn to read the log and retry – times every PR, every agent, every day.'),
    p('<strong>The subtle part:</strong> CI <em>still</em> runs every check. It stays the binding, binary bar. If a hook is ever skipped, the bar still holds. But checks about form rather than function <strong>can’t fail anymore</strong> – by the time a commit exists, they’ve already been applied. The minimum bar is secured <em>before</em> it’s ever tested. And it creates <strong>zero friction</strong>: not for people. Not for agents.'),
    quote('Agents write code &amp; features – not formatting. Tools format, sort, flag. People judge the product.'),
    p('There’s no universal preset to copy. The right config is the one that fits <em>your</em> stack, <em>your</em> repo, <em>your</em> CI budget, <em>your</em> team – decided once, versioned with the code, identical on every laptop, in every agent sandbox and in CI, and fast enough that <strong>nobody is ever tempted to bypass it</strong>. Get that right, and everyone does what they’re best at: tools do what they were built for. Agents spend their iterations on behaviour. People spend theirs on the product.'),

    h2('The last mile: one click from “done” to “try it”'),
    p('Back to that corner: merging without clicking through the feature yourself. Usually not laziness. It’s that <strong>trying it is simply harder than it should be.</strong> That’s a CI/CD problem, not a discipline problem.'),
    p('Agents write a feature in minutes. Well-configured gates prove the minimum bar minutes later. Then it reaches a person – and <strong>everything stops</strong>. To see it: check out the branch, install dependencies, dig up tokens, run migrations, seed data, hope your local setup matches. Local AI tools and skills take away some of the grind, but: context switch. Minutes to hours. A reason to skip it.'),
    p('<strong>That’s where the speed quietly leaks out.</strong> Nothing gained if writing is automated but validating stays the bottleneck. Good gates say: “the change is sound.” They <em>can’t</em> say: “it’s right – for your team, for your users.” If the check is expensive, it gets skipped. And the cut corner becomes the process.'),
    quote('Writing a feature in minutes doesn’t make you fast if trying it eats an afternoon.'),
    p('So: <strong>make trying it the cheapest step.</strong> Every change gets its own environment, built by the pipeline:'),
    {
      type: 'list',
      variant: 'ready',
      items: [
        'A link for every change – or an installable build for apps, desktop, CLIs',
        'Its own data: migrations applied, realistic seed data, test accounts ready',
        'Secrets &amp; integrations already wired in – nobody passes tokens around',
        'The same gates &amp; config as prod – just disposable',
        'Automatic teardown on merge or close',
        'A notification when it’s ready – not a dashboard you have to watch',
      ],
    },
    {
      type: 'toast',
      title: 'Hey, I’m done — your preview is ready',
      meta: 'checkout-redesign · gates passed · migrations applied',
      primary: 'Open preview',
      secondary: 'Download build',
      time: 'now',
      caption: 'This is what “done” has to look like: a ping. A link. A decision.',
    },
    p('Then the loop closes the way it should. Agent done, gates green, you get a ping. Click the link or download the build. Use it like a user. Poke at the edge cases. Decide – ship it, or hand the next steps and focus points back to the agents. <strong>Minutes. Not an afternoon.</strong> That’s “fast with confidence”: not just fast output. Fast, cheap, honest validation.'),

    h2('Why AI gets clunky in enterprise workflows'),
    p('Most large orgs adopt AI the same way: take the existing process – tickets, handoffs, approvals, sprint ceremonies – and give every step an assistant. Feels safe. Demos well. But: <strong>the process was designed around human bottlenecks.</strong> A system only moves as fast as its slowest gate.'),
    {
      type: 'frictions',
      items: [
        { title: 'Human gates sized for human output', text: 'An agent delivers a working change in minutes. Automated checks verify it in minutes more. Then it waits days for ticket refinement, a review slot, the change advisory board, the release train – all designed around human pace. The speed-up evaporates in the queue.' },
        { title: 'Context trapped in heads &amp; meetings', text: 'Agents are only as good as their context. When requirements live in hallway chats, tribal knowledge and slide decks, the AI guesses – and people spend the time they saved correcting it.' },
        { title: 'Tools &amp; permissions built for people', text: 'Access per person. Hand-provisioned environments. Nothing safe to run unattended. Agents end up in sandboxes so tight they can’t do real work. Or never get in at all.' },
        { title: 'Metrics that measure the old process', text: 'Story points, closed tickets, lines of code = proxies for human effort. Measured with the old yardsticks, AI looks either miraculous or useless – rarely what <em>actually</em> changed for users.' },
        { title: 'AI as a feature, not a rethink', text: 'Rolling out a chat assistant to every team = easy to announce, easy to measure in licences. It improves individual tasks by a few percent. While the system around it stays <em>exactly as slow</em>.' },
      ],
    },
    quote('Speeding up single steps in a process built for humans mostly makes <strong>the queues longer</strong>. The work gets faster. The outcome doesn’t.'),
    p('My expectation: most companies that go about it this way will struggle to show meaningful improvement. They’ll see islands of productivity, lots of licences, and a delivery speed that looks suspiciously like last year’s. Not because the models aren’t good enough – but because the org was never redesigned to use them.'),

    h2('Shared memory, different perspectives'),
    p('Two of those frictions – context in heads, tools built for people – aren’t process problems. <strong>They’re infrastructure problems.</strong> With infrastructure answers. The first one: memory.'),
    p('Personal project? Memory is simple: start Claude Code, turn memory on, and it gradually learns the codebase, the conventions, your preferences. One person, one repo – that’s enough.'),
    p('In an org, that model breaks. Every agent starts from zero. Its own repo. Its own sandbox. Its own session. The agent in the payments service doesn’t know what the checkout team decided last week. The agent in the mobile app doesn’t know the API it calls is being retired. Nobody remembers why two products share a login. Every agent: <strong>locally correct, globally lost.</strong>'),
    p('So memory has to become <strong>shared infrastructure</strong>: available to every agent, at every step, across products &amp; microservices. Product principles. Architecture. Contracts between services. Decisions <em>and their why</em>. Vocabulary. Known pitfalls. So that even an agent in an isolated repo or environment knows: other products exist. What they expect. How it all holds together. The missing piece most multi-repo orgs never had – <strong>not even for their people.</strong>'),
    p('And it has to be <strong>orchestratable by people</strong>. Memory is where people steer at scale: correct a wrong assumption once → every agent stops making it. Shift a priority → every agent sees it. Meaning: owned, reviewable, versioned. Not a heap of chat transcripts nobody can edit.'),
    {
      type: 'memory',
      label: 'Agents reading the same memory, each with its own perspective',
      tag: 'Shared memory',
      items: 'Principles · architecture · contracts · decisions &amp; why · vocabulary · known pitfalls',
      owner: 'curated by people',
      perspectives: [
        { lens: 'Goalpost', title: 'Refines the goal', text: 'What are we solving, for whom, what is success? Moves the target with every learning.' },
        { lens: 'Acceptance', title: 'Defines “done”', text: 'Intent → criteria, edge cases, tests that everyone builds and checks against.' },
        { lens: 'Usability', title: 'Judges the experience', text: 'Walks the flows like a user – clarity, a11y, empty and error states, feel.' },
        { lens: 'Architecture', title: 'Guards the seams', text: 'Checks every change against the contracts between products and services.' },
      ],
    },
    p('The key: <strong>agents with perspectives.</strong> They all read the same memory. But each one focuses on a different aspect. One refines the goalpost. One owns acceptance. One judges usability. One guards the seams. Same facts, different lenses. When they disagree → it surfaces early, in the open, where a person can settle it – instead of late, in prod.'),

    h2('Guardrails: your taste, written down'),
    p('Agents can do a lot – <strong>which is exactly why they need to know what NOT to do.</strong> Every product has its own taste in do’s and don’ts: patterns you use, and ones you’ve banned. Libraries you trust. How errors are handled. What never goes into a log. Which data never leaves a region. How the interface talks to people. When to ask instead of guess.'),
    p('Those rules deserve the same treatment as your CI/CD tooling: <strong>written down. Versioned. Reviewed. Applied everywhere automatically.</strong> But with one big difference: lint config = set once, rarely touched. Guardrails <strong>live with the product</strong> – they change as it matures, as the team learns, as the market and regulation move. They need an owner, a history and a place in the regular conversation.'),
    {
      type: 'table',
      variant: 'compare',
      head: ['', 'Lint &amp; CI config', 'Guardrails'],
      rows: [
        ['Encodes', 'Form &amp; known bug patterns', 'Taste, boundaries, judgement'],
        ['Changes', 'Rarely, if ever', 'Continuously, with the product'],
        ['Checked by', 'Deterministic tools', 'Agents, reviewers, people'],
        ['Written for', 'Machines', 'Agents <strong>and</strong> developers alike'],
      ],
    },
    p('That last row matters more than it looks. Guardrails should <strong>not be exclusive to agents</strong>. Written well, they’re the clearest statement of how <em>your team builds</em> – and they hold just as well in a developer’s head. The same page that stops an agent from adding yet another state library reminds a new hire <em>why</em> you don’t – and gives a reviewer something better than “I don’t like it.”'),
    quote('If a rule only lives in a prompt, it isn’t a guardrail – it’s a secret.'),
    p('Which brings us to the step most orgs miss: <strong>the right infrastructure for the architecture.</strong> When every team wires up its own agents, every repo ends up with its own copy of the guardrails, its own MCP servers, its own keys, its own idea of what’s “allowed” – drifting apart from day one. <strong>Put the shared pieces in one place:</strong> one gateway in front of inference (or a proxy in front of it) that <strong>every</strong> agent and <strong>every</strong> developer tool goes through.'),
    {
      type: 'gateway',
      clients: [
        { who: 'Agent', where: 'checkout repo' },
        { who: 'Agent', where: 'payments service' },
        { who: 'Agent', where: 'CI pipeline' },
        { who: 'Developer', where: 'IDE' },
      ],
      title: 'One gateway to inference',
      sub: 'or a proxy in front of it — every agent &amp; dev tool goes through here',
      chips: ['Guardrails', 'Shared memory', 'Shared MCP servers', 'Access &amp; audit', 'Cost &amp; model routing'],
      models: 'Models',
      caption: 'Isolated where it matters. Shared where it should be.',
    },
    p('That’s where guardrails get applied. That’s where memory gets served. That’s where MCP servers are shared instead of re-implemented in every repo. That’s where access, audit, cost and model choice are managed <strong>once</strong>. Change a guardrail once → every agent picks it up on its next request. That’s not overhead. That’s what makes <strong>100 agents behave like one team.</strong>'),

    h2('What works instead'),
    p('Teams that pull off step changes <strong>don’t add AI to their workflow – they rebuild the workflow</strong> so that people, agents and gates each do what they’re best at.'),
    {
      type: 'list',
      variant: 'checklist',
      items: [
        '<strong>Define intent &amp; acceptance criteria upfront</strong> – clear enough that an agent knows when it’s done.',
        '<strong>Invest in gates before the agents arrive:</strong> strict linting, types, tests, CodeQL/Sonar, preview builds on <em>every</em> change.',
        '<strong>Let tools fix what they can <em>before</em> anything is committed</strong> – formatting, whitespace, import/key order – so CI never fails on style and nobody reviews it.',
        '<strong>Make memory shared infrastructure:</strong> principles, architecture, contracts and decisions available to every agent at every step – curated &amp; correctable by people.',
        '<strong>Write guardrails down like config, but keep them alive</strong> – owned, versioned, shared with developers, served from one gateway together with memory &amp; MCP servers.',
        '<strong>Give agents real, scoped environments</strong> – safe to run unattended, easy to throw away.',
        '<strong>Give every change a preview</strong> – a link or installable build, with data &amp; secrets wired in – and a ping when it’s ready, so human review moves from the diff to the product.',
        '<strong>Small teams &amp; end-to-end ownership</strong> – so the loop from idea to shipped doesn’t splinter across handoffs.',
        '<strong>Measure outcomes, not output:</strong> protect time for reflection, watching real users, comparing options side by side – <strong>that’s where good becomes great.</strong>',
        '<strong>Start small, end to end:</strong> one product, one team, one value stream redesigned <em>properly</em> beats AI sprinkled across 100 unchanged processes.',
      ],
    },
    p('The more work agents take on, the more the human part – <strong>taste, judgement, empathy for the people using the thing, and accountability when it ships</strong> – becomes the actual job.'),
    h2('In practice: the staff engineer'),
    p('Look, I’m sitting here watching what’s happening in the teams around me right now. And honestly? A year ago I’d have called half of it science fiction.'),
    p('There’s this senior developer at a mid-sized company near Frankfurt. Last year he was still lead developer. Today? He’s “demoted” himself – officially just “staff engineer” now. No team, no people management, no more sprint plannings to moderate. <strong>And he earns considerably more than before.</strong> Because he’s finally doing what he’s actually paid for: making architecture decisions. Translating product vision into technical reality. Being experienced enough to say, “This will fail in six months, because …” – and then letting the agents work out the details while he’s already on the next lever.'),
    p('The guy barely types code anymore. He <em>thinks</em> code. And the agents? They type. In parallel. Ten files at once. Tests included. Documentation along with it. He only reviews the places where experience makes the difference: interfaces between services. Data models that have to survive. The one abstraction that either carries everything or breaks everything.'),
    p('The three roles weren’t decided in a meeting. They just happened.'),
    p('<strong>Human – intent.</strong> Not “writing user stories”. Standing at the whiteboard with the product owner and arguing: “Do we build this <em>now</em>, or do we first pull the technical debt out of the payment module? Because if we don’t, the next feature request blocks us for three months.” The stakeholder wants everything yesterday. The human translates: “Okay, we deliver feature X in two weeks – but only if we do the refactor in the auth service <em>at the same time</em>. Agent, plan that out.”'),
    p('<strong>Agent – build.</strong> It gets the brief: “Refactor the auth service <em>and</em> feature X in parallel. Here are the constraints: no breaking changes to the API. Tests must stay green. The migration must be rollback-safe.” And the agent? Starts <em>immediately</em>. Not after sprint start. Not after ticket refinement. Immediately. It writes the migration plan. It writes the tests <em>for the new code</em> before the new code exists. It tries three variants – one with event sourcing, one classic, one hybrid – and puts three PRs in front of the human at 8:30 in the morning: “Option A: safer, two weeks. Option B: faster, technical risk here. Option C: cleanest architecture, but three more days of work.”'),
    p('<strong>Gates – pass/fail.</strong> The gates? They don’t sleep. They check <em>every</em> variant. Types, lint, unit, integration, E2E, CodeQL, Sonar, bundle size, a11y. Variant B drops out – the security scan finds something. Variants A and C pass. The human clicks through the previews (built <em>automatically</em>, with real data, real secrets, real everything), tries the edge cases, nods at option C: “Take that one. Merge. Ship.”'),
    p('While he’s deciding, the agents have long started preparing the next thing. Because they have the context. Because they share the memory. Because they know: “Ah, the auth refactor is through – so now I can cleanly wire in the feature flag for the new payment method.”'),

    h2('What this does to roles'),
    quote('The crazy part: <strong>this is already happening. Today. In real companies.</strong>'),
    p('Not in demos. Not in side projects. In production systems that make money.'),
    p('The regular devs? Many are leaving. Not because they’re bad – because they can <em>only</em> code. And coding is now the cheapest activity in the whole stack. Whoever “just” works through tickets gets replaced. Not by AI – by <strong>one senior + agents</strong>, getting ten times as much done.'),
    p('The ones who stay? They become <em>more valuable</em>. Much more valuable. Because their expertise suddenly <strong>scales</strong>. An architect who used to look after three teams now looks after fifteen – because the agents do the legwork juniors used to do. And the juniors? There are hardly any left. At least not in the classic sense. The junior role is shifting: whoever starts out today doesn’t learn “how do I write a function?” – they learn “how do I phrase intent precisely enough that the agent builds the right thing?” and “how do I tell whether the result is <em>actually</em> good?”'),

    h2('People still work with people'),
    p('But – and this is the part all those “AI replaces programmers” articles never get – <strong>people still work primarily with people.</strong>'),
    p('Feature prioritisation? An agent can generate a list of 200 tasks for you, neatly estimated, with dependencies, risks and impact scores. Impressive. But <em>which</em> of them do we build <em>now</em>? A human negotiates that with stakeholders. That’s politics. That’s trust. That’s: “Customer X threatens to leave if we don’t deliver feature Y next month – but if we build Y, we break Z for customer A, our biggest source of revenue. What do we do?”'),
    quote('No agent decides that. No agent <em>should</em> decide that.'),
    p('What the agent <em>can</em> do is tell you: “If we build Y, we break Z <em>here</em> and <em>here</em> – here are the affected tests, here’s the migration effort, here are three options to save Z. Option 1 costs two weeks. Option 2 costs three days, but we need a feature flag. Option 3: we tell customer A they have to migrate – here’s the migration guide I’ve already prepared.”'),
    p('The human decides. In minutes. Not in two weeks of architecture review meetings.'),

    h2('Refactor first – with numbers, not gut feeling'),
    p('Refactoring before a new feature? It used to be: “We’ll do it later. Create a Jira ticket. Forget about it.” Today, the agent analyses the codebase, finds the hotspots and simulates the impact: “If we build feature X <em>without</em> the refactor, the change failure rate in the payment module goes up by 34%. The refactor costs 4 agent-days. Feature X alone, 6 days. Feature X <em>with</em> the refactor, 8 days – but after that, the next feature is 40% faster.” The human looks at the numbers. Nods. “Do the refactor first. I’ll tell the PO feature X comes two days later, but the next three features go faster.”'),
    p('And while the human explains that to the PO, the agent has <em>already started</em> the refactor. Not “planned” it. Started. Branches created. Tests written. First commits pushed. CI running. Previews ready.'),

    h2('Not the future: last Tuesday'),
    p('This isn’t some distant future. It happened <strong>last Tuesday</strong>. In a team I know. Five people. Two seniors, one mid, two “agent orchestrators” – a new role with its own salary band. They shipped in one week what used to take them six. With <em>better</em> code quality. Because the gates don’t get tired. Because the agents don’t do “quick, quick” but “right, right” – because a human told them what “right” looks like.'),
    p('And the best part? <strong>The senior developers go home happy again.</strong> Not because they work less – because they work on <em>the right things</em>. Architecture. Product. Mentoring. The decisions that need experience. The typing? The agents handle it. While the human drinks coffee and argues with the product owner.'),
    p('The companies that get this? They’re hiring right now. Not “developers”. <strong>Architects with agent fleets.</strong> And they pay them accordingly.'),
    p('The companies still “integrating AI assistants into Jira”? Next year they’ll be asking why their velocity didn’t go up – while their best people quit, because somewhere else they’re paid considerably better for exactly the work they <em>actually</em> trained for.'),

    h2('The new seniority'),
    p('Up there, it was all YAML configs. Lefthook setups. Gateway architectures for shared memory. Guardrails as code. Preview pipelines that post a clickable link for every PR in Slack.'),
    p('But honestly? Those are just tools. The real game happens <strong>between your ears</strong>. And in the conversations at the whiteboard. And in the question you ask yourself every morning:'),
    quote('What’s the lever today that only I can move – and how do I get the agents to build the rest?'),
    p('That’s the new seniority. Not “I code the fastest”. But: “I know what needs to be built – and I have the army that builds it while I’m already looking for the next lever.”'),
    p('That’s exactly why I design and build this way.'),
    {
      type: 'cta',
      text: 'How would this look in <em>your</em> setup? What would your first lever be?',
      sub: 'Let’s talk about it. No pitch. No bullshit. Just two people looking at the same problem from different angles.',
      button: 'Let’s talk',
    },
  ],
};
