backend:
  name: git-gateway
  branch: v2

publish_mode: editorial_workflow

# Media files will be stored in the repo under static/images/uploads
media_folder: "backend/assets/"

# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/content/assets"
